# Copied from https://github.com/huggingface/diffusers/blob/fc6acb6b97e93d58cb22b5fee52d884d77ce84d8/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
# with the following modifications:
# - It uses the patched version of `ddim_step_with_logprob` from `ddim_with_logprob.py`. As such, it only supports the
#   `ddim` scheduler.
# - It returns all the intermediate latents of the denoising process as well as the log probs of each denoising step.

from typing import Any, Callable, Dict, List, Optional, Union
import numpy as np
import torch

from diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion import (
    StableDiffusionPipeline,
    rescale_noise_cfg,
)

from .ddim_seperate_func import ddim_step_fetch_x0, ddim_step_fetch_x_t_1
import torch.nn.functional as F
from matplotlib import pyplot as plt
import contextlib


@torch.no_grad()
def pipeline_with_logprob(
    self: StableDiffusionPipeline,
    prompt: Union[str, List[str]] = None,
    height: Optional[int] = None,
    width: Optional[int] = None,
    num_inference_steps: int = 50,
    guidance_scale: float = 7.5,
    negative_prompt: Optional[Union[str, List[str]]] = None,
    num_images_per_prompt: Optional[int] = 1,
    eta: float = 0.0,
    generator: Optional[Union[torch.Generator, List[torch.Generator]]] = None,
    latents: Optional[torch.FloatTensor] = None,
    prompt_embeds: Optional[torch.FloatTensor] = None,
    negative_prompt_embeds: Optional[torch.FloatTensor] = None,
    output_type: Optional[str] = "pil",
    return_dict: bool = True,
    callback: Optional[Callable[[int, int, torch.FloatTensor], None]] = None,
    callback_steps: int = 1,
    cross_attention_kwargs: Optional[Dict[str, Any]] = None,
    guidance_rescale: float = 0.0,
    is_noise_images: bool = False, 
    pref_function=None,
    opt_func_name=None,
    divert_start_step=0,
    divert_end_step=50,
    soup_start_step=0,
    soup_end_step=0,
    extra_info=None,
    inner_steps=1,
    weights=None,
    reward_norm='std',
    sym_noise_flag=True,  #set True for SRSoup
    cor_flag=True,
    query_size=30,
    query_batch_size=15,
    record_bc_flag=False,
    reward_executor=None,
    profiler=None,
    memory_tracker=None,
    batch_idx=None,
    compress_target=-15
):
    r"""
    Function invoked when calling the pipeline for generation.

    Args:
        prompt (`str` or `List[str]`, *optional*):
            The prompt or prompts to guide the image generation. If not defined, one has to pass `prompt_embeds`.
            instead.
        height (`int`, *optional*, defaults to self.unet.config.sample_size * self.vae_scale_factor):
            The height in pixels of the generated image.
        width (`int`, *optional*, defaults to self.unet.config.sample_size * self.vae_scale_factor):
            The width in pixels of the generated image.
        num_inference_steps (`int`, *optional*, defaults to 50):
            The number of denoising steps. More denoising steps usually lead to a higher quality image at the
            expense of slower inference.
        guidance_scale (`float`, *optional*, defaults to 7.5):
            Guidance scale as defined in [Classifier-Free Diffusion Guidance](https://arxiv.org/abs/2207.12598).
            `guidance_scale` is defined as `w` of equation 2. of [Imagen
            Paper](https://arxiv.org/pdf/2205.11487.pdf). Guidance scale is enabled by setting `guidance_scale >
            1`. Higher guidance scale encourages to generate images that are closely linked to the text `prompt`,
            usually at the expense of lower image quality.
        negative_prompt (`str` or `List[str]`, *optional*):
            The prompt or prompts not to guide the image generation. If not defined, one has to pass
            `negative_prompt_embeds` instead. Ignored when not using guidance (i.e., ignored if `guidance_scale` is
            less than `1`).
        num_images_per_prompt (`int`, *optional*, defaults to 1):
            The number of images to generate per prompt.
        eta (`float`, *optional*, defaults to 0.0):
            Corresponds to parameter eta (η) in the DDIM paper: https://arxiv.org/abs/2010.02502. Only applies to
            [`schedulers.DDIMScheduler`], will be ignored for others.
        generator (`torch.Generator` or `List[torch.Generator]`, *optional*):
            One or a list of [torch generator(s)](https://pytorch.org/docs/stable/generated/torch.Generator.html)
            to make generation deterministic.
        latents (`torch.FloatTensor`, *optional*):
            Pre-generated noisy latents, sampled from a Gaussian distribution, to be used as inputs for image
            generation. Can be used to tweak the same generation with different prompts. If not provided, a latents
            tensor will ge generated by sampling using the supplied random `generator`.
        prompt_embeds (`torch.FloatTensor`, *optional*):
            Pre-generated text embeddings. Can be used to easily tweak text inputs, *e.g.* prompt weighting. If not
            provided, text embeddings will be generated from `prompt` input argument.
        negative_prompt_embeds (`torch.FloatTensor`, *optional*):
            Pre-generated negative text embeddings. Can be used to easily tweak text inputs, *e.g.* prompt
            weighting. If not provided, negative_prompt_embeds will be generated from `negative_prompt` input
            argument.
        output_type (`str`, *optional*, defaults to `"pil"`):
            The output format of the generate image. Choose between
            [PIL](https://pillow.readthedocs.io/en/stable/): `PIL.Image.Image` or `np.array`.
        return_dict (`bool`, *optional*, defaults to `True`):
            Whether or not to return a [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] instead of a
            plain tuple.
        callback (`Callable`, *optional*):
            A function that will be called every `callback_steps` steps during inference. The function will be
            called with the following arguments: `callback(step: int, timestep: int, latents: torch.FloatTensor)`.
        callback_steps (`int`, *optional*, defaults to 1):
            The frequency at which the `callback` function will be called. If not specified, the callback will be
            called at every step.
        cross_attention_kwargs (`dict`, *optional*):
            A kwargs dictionary that if specified is passed along to the `AttentionProcessor` as defined under
            `self.processor` in
            [diffusers.cross_attention](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/cross_attention.py).
        guidance_rescale (`float`, *optional*, defaults to 0.7):
            Guidance rescale factor proposed by [Common Diffusion Noise Schedules and Sample Steps are
            Flawed](https://arxiv.org/pdf/2305.08891.pdf) `guidance_scale` is defined as `φ` in equation 16. of
            [Common Diffusion Noise Schedules and Sample Steps are Flawed](https://arxiv.org/pdf/2305.08891.pdf).
            Guidance rescale factor should fix overexposure when using zero terminal SNR.

    Examples:

    Returns:
        [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] or `tuple`:
        [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] if `return_dict` is True, otherwise a `tuple.
        When returning a tuple, the first element is a list with the generated images, and the second element is a
        list of `bool`s denoting whether the corresponding generated image likely represents "not-safe-for-work"
        (nsfw) content, according to the `safety_checker`.
    """
    # if query_batch_size > query_size:
    #     query_batch_size = query_size
    # if (query_size//query_batch_size)*query_batch_size < query_size:
    #     query_batch_size = query_size//2
    #assert query_size%query_batch_size==0
    if profiler is not None:
        profiler.start('pipeline_inference')
    # 0. Default height and width to unet
    height = height or self.unet.config.sample_size * self.vae_scale_factor
    width = width or self.unet.config.sample_size * self.vae_scale_factor

    # 1. Check inputs. Raise error if not correct
    self.check_inputs(prompt, height, width, callback_steps, negative_prompt, prompt_embeds, negative_prompt_embeds)

    # 2. Define call parameters
    if prompt is not None and isinstance(prompt, str):
        batch_size = 1
    elif prompt is not None and isinstance(prompt, list):
        batch_size = len(prompt)
    else:
        batch_size = prompt_embeds.shape[0]

    device = self._execution_device
    # here `guidance_scale` is defined analog to the guidance weight `w` of equation (2)
    # of the Imagen paper: https://arxiv.org/pdf/2205.11487.pdf . `guidance_scale = 1`
    # corresponds to doing no classifier free guidance.
    do_classifier_free_guidance = guidance_scale > 1.0
    
    # 4. Prepare timesteps
    self.scheduler.set_timesteps(num_inference_steps, device=device)
    timesteps = self.scheduler.timesteps
    
    # 3. Encode input prompt
    text_encoder_lora_scale = cross_attention_kwargs.get("scale", None) if cross_attention_kwargs is not None else None
    prompt_embeds, negative_prompt_embeds = self.encode_prompt(
        prompt,
        device,
        num_images_per_prompt,
        do_classifier_free_guidance,
        negative_prompt,
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        lora_scale=text_encoder_lora_scale,
    )
    
    log_prompt_embeds = prompt_embeds
    # For classifier free guidance, we need to do two forward passes.
    # Here we concatenate the unconditional and text embeddings into a single batch
    # to avoid doing two forward passes

    if do_classifier_free_guidance:
        prompt_embeds = torch.cat([negative_prompt_embeds, log_prompt_embeds])
        prev_prompt_embeds = torch.cat([
            negative_prompt_embeds.repeat(query_batch_size, 1, 1),
            log_prompt_embeds.repeat(query_batch_size, 1, 1),
        ])
    else:
        prev_prompt_embeds = log_prompt_embeds.repeat(query_batch_size, 1, 1)

    # 5. Prepare latent variables
    num_channels_latents = self.unet.config.in_channels
    latents = self.prepare_latents(
        batch_size * num_images_per_prompt,
        num_channels_latents,
        height,
        width,
        prompt_embeds.dtype,
        device,
        generator,
        latents,
    )

    # 6. Prepare extra step kwargs. TODO: Logic should ideally just be moved out of the pipeline
    extra_step_kwargs = self.prepare_extra_step_kwargs(generator, eta)

    # 7. Denoising loop
    num_warmup_steps = len(timesteps) - num_inference_steps * self.scheduler.order
    all_latents = [latents]
    all_log_probs = []
    preference_score_logs = []
    
    if divert_start_step == 0:
        latents = latents.repeat(len(weights), 1, 1, 1)
        if do_classifier_free_guidance:
            prompt_embeds = torch.cat([
                negative_prompt_embeds.repeat(len(weights), 1, 1),
                log_prompt_embeds.repeat(len(weights), 1, 1),
            ])
    
    with (self.progress_bar(total=num_inference_steps) as progress_bar):
        for i, t in enumerate(timesteps):
            for j in range(inner_steps):
                # expand the latents if we are doing classifier free guidance
                latent_model_input = torch.cat([latents] * 2) if do_classifier_free_guidance else latents
                latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)
                print(latent_model_input.dtype, prompt_embeds.dtype)
                
                """
                Record Bhattacharyya Coefficient 
                """
                if record_bc_flag:
                    if i > 0:
                        variance_scale = torch.mean(prev_latents_std)**2
                    else:
                        variance_scale = 1
                    diff = (latents[0]-latents[len(weights)-1])**2
                    print(t, torch.sum(diff), torch.mean(diff), variance_scale)
                    print(t, torch.exp(-1/(8*variance_scale)*(torch.mean(diff))))

                # predict the noise residual
                noise_pred = self.unet(
                    latent_model_input,
                    t,
                    encoder_hidden_states=prompt_embeds,
                    cross_attention_kwargs=cross_attention_kwargs,
                    return_dict=False,
                )[0]
                
                # perform guidance
                if do_classifier_free_guidance:
                    noise_pred_uncond, noise_pred_text = noise_pred.chunk(2)
                    noise_pred = noise_pred_uncond + guidance_scale * (noise_pred_text - noise_pred_uncond)

                if do_classifier_free_guidance and guidance_rescale > 0.0:
                    # Based on 3.4. in https://arxiv.org/pdf/2305.08891.pdf
                    noise_pred = rescale_noise_cfg(noise_pred, noise_pred_text, guidance_rescale=guidance_rescale)

                if t == 1 and extra_info['prompts'] == 'lobster':
                    pred_dict = ddim_step_fetch_x0(
                        self.scheduler,
                        noise_pred, 
                        t, 
                        latents, 
                    )
                    latents = pred_dict['pred_original_sample']
                    # latents = ddim_step_fetch_x_t_1(
                    #     self.scheduler,
                    #     dtype=latents.dtype,
                    #     num_sample_per_step=1,
                    #     timestep=t,
                    #     **extra_step_kwargs,
                    #     **pred_dict,
                    # )
                elif divert_end_step > i >= divert_start_step:
                    if  soup_start_step <= i < soup_end_step:    # i < ws_start_step
                        prev_latents = [[] for i in range(len(weights))]      
                        if opt_func_name[1] == 'compress' and sym_noise_flag:  
                            if query_size%2 == 0:
                                latent_shape = (query_size//2,)+latents.shape[1:]
                                tmp = torch.randn(latent_shape).to(device=device, dtype=latents.dtype)
                                all_prev_latents_noise = torch.cat([tmp, -tmp], dim=0)
                            else:
                                latent_shape = (query_size//2+1,)+latents.shape[1:]
                                tmp = torch.randn(latent_shape).to(device=device, dtype=latents.dtype)
                                all_prev_latents_noise = torch.cat([tmp, -tmp], dim=0)
                                all_prev_latents_noise = all_prev_latents_noise[:query_size]
                        else:
                            all_prev_latents_noise = [None for i in range(query_size)]
                        
                        anchor_ws_index = [0, len(weights)-1]
                        anchor_prev_means = []

                        pred_dict_w01 = []
                        for idx in anchor_ws_index:     
                            latents_i = latents[idx].unsqueeze(0)
                            pred_dict = ddim_step_fetch_x0(
                                self.scheduler,
                                noise_pred[idx].unsqueeze(0),
                                t,
                                latents_i,
                            )
                            pred_dict_w01.append(pred_dict)
                        
                        del latents_i, pred_dict

                        all_rewards_1 = []
                        all_rewards_2 = []
                            
                        for k in range(query_size//query_batch_size):
                            prev_pred_x0_w01 = []
                            for _, idx in enumerate(anchor_ws_index):     
                                prev_latents_noise = all_prev_latents_noise[k*query_batch_size:(k+1)*query_batch_size]
                                pred_dict = pred_dict_w01[_]
                                prev_latents_ik, prev_latents_mean, prev_latents_std, prev_latents_noise = ddim_step_fetch_x_t_1(
                                    self.scheduler,
                                    dtype=latents.dtype,
                                    num_sample_per_step=query_batch_size,
                                    timestep=t,
                                    return_prev_mean=True,
                                    variance_noise=prev_latents_noise,
                                    **extra_step_kwargs,
                                    **pred_dict,  # noise is same for different weightings, but latents_k are different.
                                )

                                if k == 0:  # save prev_latents_mean for later usage
                                    anchor_prev_means.append(prev_latents_mean)

                                if all_prev_latents_noise[k*query_batch_size] is None:
                                    all_prev_latents_noise[k*query_batch_size:(k+1)*query_batch_size] = prev_latents_noise
                                else:
                                    pass

                                # Profiling decoding x_t-1 for reward query
                                decode_ctx = profiler.profile(f"decoding_for_reward_query_batch-{batch_idx}") if profiler else contextlib.nullcontext()
                                with decode_ctx:
                                    latent_model_input = torch.cat([prev_latents_ik] * 2) if do_classifier_free_guidance else prev_latents_ik
                                    latent_model_input = self.scheduler.scale_model_input(latent_model_input, pred_dict['prev_timestep'])
                                    # predict the noise residual
                                    prev_noise_pred = self.unet(
                                        latent_model_input,
                                        pred_dict['prev_timestep'],
                                        encoder_hidden_states=prev_prompt_embeds,
                                        cross_attention_kwargs=cross_attention_kwargs,
                                        return_dict=False,
                                    )[0]
                                    # perform guidance
                                    if do_classifier_free_guidance:
                                        noise_pred_uncond, noise_pred_text = prev_noise_pred.chunk(2)
                                        prev_noise_pred = noise_pred_uncond + guidance_scale * (noise_pred_text - noise_pred_uncond)
                                    if do_classifier_free_guidance and guidance_rescale > 0.0:
                                        # Based on 3.4. in https://arxiv.org/pdf/2305.08891.pdf
                                        prev_noise_pred = rescale_noise_cfg(prev_noise_pred, noise_pred_text, guidance_rescale=guidance_rescale)
                                    prev_pred_dict = ddim_step_fetch_x0(
                                        self.scheduler,
                                        prev_noise_pred,
                                        pred_dict['prev_timestep'],
                                        prev_latents_ik,
                                    )
                                    # num_sample_per_step+1, c, h, w
                                    prev_pred_x0 = prev_pred_dict['pred_original_sample']
                                    prev_pred_x0 = self.vae.decode(
                                        prev_pred_x0.to(self.vae.dtype) / self.vae.config.scaling_factor,
                                        return_dict=False,
                                        generator=generator,
                                    )[0]
                                    prev_pred_x0_w01.append(prev_pred_x0)  # prev_pred_x0_w01[1] for f1; prev_pred_x0_w01[0] for f2
                        
                            # Start profiling _compute_reward calls for soup phase
                            reward_ctx = profiler.profile(f"soup_reward_compute_batch-{batch_idx}") if profiler else contextlib.nullcontext()
                            with reward_ctx:
                                if reward_executor is not None:  
                                    # Submit both reward computations in parallel
                                    future_func1 = reward_executor.submit(
                                        self._compute_reward,
                                        prev_pred_x0_w01[1], opt_func_name[0], pref_function[0],
                                        extra_info, query_batch_size, compress_target, device
                                    )
                                    future_func2 = reward_executor.submit(
                                        self._compute_reward,
                                        prev_pred_x0_w01[0], opt_func_name[1], pref_function[1],
                                        extra_info, query_batch_size, compress_target, device
                                    )
                                    
                                    # Wait for both results - this is where _compute_reward actually executes
                                    try:
                                        func1_scores = future_func1.result(timeout=100)  # Add timeout
                                        func2_scores = future_func2.result(timeout=100)
                                    except Exception as e:
                                        # Log error and fall back to sequential
                                        print(f"Parallel reward computation failed: {e}")
                                else:
                                    # Fallback to sequential if parallel disabled
                                    func1_scores = self._compute_reward(
                                        prev_pred_x0_w01[1], opt_func_name[0], pref_function[0],
                                        extra_info, query_batch_size, compress_target, device
                                    )
                                    func2_scores = self._compute_reward(
                                        prev_pred_x0_w01[0], opt_func_name[1], pref_function[1],
                                        extra_info, query_batch_size, compress_target, device
                                    )
                            
                            all_rewards_1.append(func1_scores)
                            all_rewards_2.append(func2_scores)
                            
                        # Stack noise if list
                        if isinstance(all_prev_latents_noise, list):
                            all_prev_latents_noise = torch.stack(all_prev_latents_noise, dim=0)

                        all_rewards_1 = torch.cat(all_rewards_1, dim=0)
                        all_rewards_2 = torch.cat(all_rewards_2, dim=0)
                        
                        # Normalize both rewards
                        if opt_func_name[0] == 'compress':
                            all_rewards_1_nor = self._normalize_rewards(all_rewards_1, reward_norm, compress_target)
                        else:
                            all_rewards_1_nor = self._normalize_rewards(all_rewards_1, reward_norm)
                        if opt_func_name[1] == 'compress':
                            all_rewards_2_nor = self._normalize_rewards(all_rewards_2, reward_norm, compress_target)
                        else:
                            all_rewards_2_nor = self._normalize_rewards(all_rewards_2, reward_norm)
                        
                        latent_dim = np.prod(latents.shape[1:])
                        for _, idx in enumerate(anchor_ws_index):
                            if _ == 0:
                                if opt_func_name[1] == 'compress':
                                    k = all_rewards_2_nor.shape[0]//6
                                    vals, top_idx = torch.topk(all_rewards_2_nor, k)
                                    mask = torch.zeros_like(all_rewards_2_nor)
                                    mask.scatter_(dim=-1, index=top_idx, value=1.0)
                                    all_rewards_2_nor_ = all_rewards_2_nor * mask
                                else:
                                    all_rewards_2_nor_ = all_rewards_2_nor
                                all_rewards_2_nor_ = all_rewards_2_nor_.reshape(-1, 1, 1, 1)
                                prev_noise_2_mean = torch.sum(all_rewards_2_nor_ * all_prev_latents_noise, dim=0, keepdim=True)
                                prev_noise_mean = prev_noise_2_mean
                            else:
                                all_rewards_1_nor = all_rewards_1_nor.reshape(-1, 1, 1, 1)
                                prev_noise_1_mean = torch.sum(all_rewards_1_nor * all_prev_latents_noise, dim=0, keepdim=True)
                                prev_noise_mean = prev_noise_1_mean
                            if prev_noise_mean.norm()>0:
                                prev_noise_mean = prev_noise_mean/((prev_noise_mean ** 2).sum(dim=[1, 2, 3], keepdim=True).sqrt()+1e-8)*(latent_dim**0.5)
                            prev_sample = anchor_prev_means[_] + prev_latents_std * prev_noise_mean
                            prev_latents_i = prev_sample
                            prev_latents[idx] = prev_latents_i
                            
                        remaining_ws_indx = np.delete(np.arange(len(weights)), anchor_ws_index)
                        all_rewards_1_nor = all_rewards_1_nor.reshape(-1, 1, 1, 1)
                        all_rewards_2_nor = all_rewards_2_nor.reshape(-1, 1, 1, 1)
                        for idx in remaining_ws_indx:
                            latents_i = latents[idx].unsqueeze(0)
                            pred_dict = ddim_step_fetch_x0(
                                self.scheduler,
                                noise_pred[idx].unsqueeze(0),
                                t,
                                latents_i,
                            )
                            _, prev_latents_mean, prev_latents_std, _ = ddim_step_fetch_x_t_1(
                                    self.scheduler,
                                    dtype=latents.dtype,
                                    num_sample_per_step=1,
                                    timestep=t,
                                    return_prev_mean=True,
                                    **extra_step_kwargs,
                                    **pred_dict,  # noise is same for different weightings, but latents_k are different.
                                )
                            w = weights[idx]
                            #prev_noise_mean = w*anchor_bo_grads[1]+(1-w)*anchor_bo_grads[0]
                            if cor_flag == False:
                                w_all_rewards = (w*all_rewards_1_nor+(1-w)*all_rewards_2_nor).reshape(-1, 1, 1, 1)
                                prev_noise_mean = torch.sum(w_all_rewards * all_prev_latents_noise, dim=0, keepdim=True)
                            else:
                                all_prev_latents_noise_cor_1 = (all_prev_latents_noise+(anchor_prev_means[1]-prev_latents_mean))
                                all_prev_latents_noise_cor_1 = all_prev_latents_noise_cor_1/(all_prev_latents_noise_cor_1 ** 2).sum(axis=[1, 2, 3], keepdim=True).sqrt()*(latent_dim**0.5)
                                prev_noise_mean_1 = torch.sum(all_rewards_1_nor*all_prev_latents_noise_cor_1, dim=0, keepdim=True)
                                #prev_noise_mean_1 = prev_noise_mean_1/((prev_noise_mean_1**2).sum(dim=[1, 2, 3], keepdim=True).sqrt()+1e-8)*(latent_dim**0.5)
                                all_prev_latents_noise_cor_2 = (all_prev_latents_noise+(anchor_prev_means[0]-prev_latents_mean))
                                all_prev_latents_noise_cor_2 = all_prev_latents_noise_cor_2/(all_prev_latents_noise_cor_2 ** 2).sum(axis=[1, 2, 3], keepdim=True).sqrt()*(latent_dim**0.5)
                                prev_noise_mean_2 = torch.sum(all_rewards_2_nor*all_prev_latents_noise_cor_2, dim=0, keepdim=True)
                                #prev_noise_mean_2 = prev_noise_mean_2/((prev_noise_mean_2**2).sum(dim=[1, 2, 3], keepdim=True).sqrt()+1e-8)*(latent_dim**0.5)
                                prev_noise_mean = w*prev_noise_mean_1+(1-w)*prev_noise_mean_2

                            latent_dim = np.prod(latents.shape[1:])
                            prev_noise_mean = prev_noise_mean/((prev_noise_mean ** 2).sum(dim=[1, 2, 3], keepdim=True).sqrt()+1e-8)*(latent_dim**0.5)
                            prev_sample = prev_latents_mean + prev_latents_std * prev_noise_mean
                            prev_latents_i = prev_sample
                            prev_latents[idx] = prev_latents_i
                                
                        prev_latents = torch.cat(prev_latents, dim=0)
                        latents = prev_latents
                        torch.cuda.empty_cache()
                    else:   # weighted sum strategy
                        prev_latents = []      
                        # using symmetric noise for animal
                        if opt_func_name[1] == 'compress' and sym_noise_flag:  
                            if query_size%2 == 0:
                                latent_shape = (query_size//2,)+latents.shape[1:]
                                tmp = torch.randn(latent_shape).to(device=device, dtype=latents.dtype)
                                all_prev_latents_noise = torch.cat([tmp, -tmp], dim=0)
                            else:
                                latent_shape = (query_size//2+1,)+latents.shape[1:]
                                tmp = torch.randn(latent_shape).to(device=device, dtype=latents.dtype)
                                all_prev_latents_noise = torch.cat([tmp, -tmp], dim=0)
                                all_prev_latents_noise = all_prev_latents_noise[:query_size]
                        else:
                            all_prev_latents_noise = [None for i in range(query_size)]
                        for idx, w in enumerate(weights):     
                            latents_i = latents[idx].unsqueeze(0)
                            pred_dict = ddim_step_fetch_x0(
                                self.scheduler,
                                noise_pred[idx].unsqueeze(0),
                                t,
                                latents_i,
                            )
                            
                            all_rewards_1 = []
                            all_rewards_2 = []
                            
                            if query_size % query_batch_size == 0:
                                query_batch = query_size//query_batch_size
                            else:
                                query_batch = query_size//query_batch_size + 1
                            for k in range(query_batch):
                                if k == query_batch-1:
                                    prev_latents_noise = all_prev_latents_noise[k*query_batch_size:]
                                else:
                                    prev_latents_noise = all_prev_latents_noise[k*query_batch_size:(k+1)*query_batch_size]
                                prev_latents_k, prev_latents_mean, prev_latents_std, prev_latents_noise = ddim_step_fetch_x_t_1(
                                    self.scheduler,
                                    dtype=latents.dtype,
                                    num_sample_per_step=len(prev_latents_noise),
                                    timestep=t,
                                    return_prev_mean=True,
                                    variance_noise=prev_latents_noise,
                                    **extra_step_kwargs,
                                    **pred_dict,  # noise is same for different weightings, but latents_k are different.
                                )
                                if all_prev_latents_noise[k*query_batch_size] is None:
                                    if k == query_batch:
                                        all_prev_latents_noise[k*query_batch_size:] = prev_latents_noise
                                    else:
                                        all_prev_latents_noise[k*query_batch_size:(k+1)*query_batch_size] = prev_latents_noise
                                else:
                                    pass

                                # Profiling decoding x_t-1 for reward query
                                decode_ctx = profiler.profile(f"decoding_for_reward_query_batch-{batch_idx}") if profiler else contextlib.nullcontext()
                                with decode_ctx:
                                    latent_model_input = torch.cat([prev_latents_k] * 2) if do_classifier_free_guidance else prev_latents_k
                                    latent_model_input = self.scheduler.scale_model_input(latent_model_input, pred_dict['prev_timestep'])
                                    # predict the noise residual
                                    if do_classifier_free_guidance:
                                        prev_prompt_embeds = torch.cat([
                                            negative_prompt_embeds.repeat(len(prev_latents_noise), 1, 1),
                                            log_prompt_embeds.repeat(len(prev_latents_noise), 1, 1),
                                        ])
                                    else:
                                        prev_prompt_embeds = log_prompt_embeds.repeat(len(prev_latents_noise), 1, 1)
                                    prev_noise_pred = self.unet(
                                        latent_model_input,
                                        pred_dict['prev_timestep'],
                                        encoder_hidden_states=prev_prompt_embeds,
                                        cross_attention_kwargs=cross_attention_kwargs,
                                        return_dict=False,
                                    )[0]
                                    # perform guidance
                                    if do_classifier_free_guidance:
                                        noise_pred_uncond, noise_pred_text = prev_noise_pred.chunk(2)
                                        prev_noise_pred = noise_pred_uncond + guidance_scale * (noise_pred_text - noise_pred_uncond)
                                    if do_classifier_free_guidance and guidance_rescale > 0.0:
                                        # Based on 3.4. in https://arxiv.org/pdf/2305.08891.pdf
                                        prev_noise_pred = rescale_noise_cfg(prev_noise_pred, noise_pred_text, guidance_rescale=guidance_rescale)
                                    prev_pred_dict = ddim_step_fetch_x0(
                                        self.scheduler,
                                        prev_noise_pred,
                                        pred_dict['prev_timestep'],
                                        prev_latents_k,
                                    )
                                    # num_sample_per_step+1, c, h, w
                                    prev_pred_x0 = prev_pred_dict['pred_original_sample']
                                    prev_pred_x0 = self.vae.decode(
                                        prev_pred_x0.to(self.vae.dtype) / self.vae.config.scaling_factor,
                                        return_dict=False,
                                        generator=generator,
                                    )[0]
                                
                                # Start profiling _compute_reward calls for weighted sum phase
                                reward_ctx = profiler.profile(f"ws_reward_compute_batch-{batch_idx}") if profiler else contextlib.nullcontext()
                                with reward_ctx:
                                    if reward_executor is not None:
                                        # Submit both reward computations in parallel
                                        future_func1 = reward_executor.submit(
                                            self._compute_reward,
                                            prev_pred_x0, opt_func_name[0], pref_function[0],
                                            extra_info, len(prev_latents_noise), compress_target, device
                                        )
                                        future_func2 = reward_executor.submit(
                                            self._compute_reward,
                                            prev_pred_x0, opt_func_name[1], pref_function[1],
                                            extra_info, len(prev_latents_noise), compress_target, device
                                        )
                                        
                                        # Wait for both results - this is where _compute_reward actually executes
                                        try:
                                            func1_scores = future_func1.result(timeout=100)  # Add timeout
                                            func2_scores = future_func2.result(timeout=100)
                                        except Exception as e:
                                            # Log error and fall back to sequential
                                            print(f"Parallel reward computation failed: {e}")
                                    else:
                                        # Fallback to sequential if parallel disabled
                                        func1_scores = self._compute_reward(
                                            prev_pred_x0, opt_func_name[0], pref_function[0],
                                            extra_info, len(prev_latents_noise), compress_target, device
                                        )
                                        func2_scores = self._compute_reward(
                                            prev_pred_x0, opt_func_name[1], pref_function[1],
                                            extra_info, len(prev_latents_noise), compress_target, device
                                        )
                                        
                                all_rewards_1.append(func1_scores)
                                all_rewards_2.append(func2_scores)
                            
                            # Stack and normalize
                            if isinstance(all_prev_latents_noise, list):
                                all_prev_latents_noise = torch.stack(all_prev_latents_noise, dim=0)
                            
                            all_rewards_1 = torch.cat(all_rewards_1, dim=0)
                            all_rewards_2 = torch.cat(all_rewards_2, dim=0)
                            
                            # Normalize both rewards
                            if opt_func_name[0] == 'compress':
                                all_rewards_1_nor = self._normalize_rewards(all_rewards_1, reward_norm, compress_target)
                            else:
                                all_rewards_1_nor = self._normalize_rewards(all_rewards_1, reward_norm)
                            if opt_func_name[1] == 'compress':
                                all_rewards_2_nor = self._normalize_rewards(all_rewards_2, reward_norm, compress_target)
                            else:
                                all_rewards_2_nor = self._normalize_rewards(all_rewards_2, reward_norm)
                            all_rewards_1_nor = all_rewards_1_nor.reshape(-1, 1, 1, 1)
                            all_rewards_2_nor = all_rewards_2_nor.reshape(-1, 1, 1, 1)
                            
                            # Weigted combination
                            prev_noise_mean_1 = torch.sum(all_rewards_1_nor * all_prev_latents_noise, dim=0, keepdim=True)
                            prev_noise_mean_2 = torch.sum(all_rewards_2_nor * all_prev_latents_noise, dim=0, keepdim=True)                                
                            prev_noise_mean = w*prev_noise_mean_1+(1-w)*prev_noise_mean_2
                            latent_dim = np.prod(latents.shape[1:])
                            prev_noise_mean = prev_noise_mean/((prev_noise_mean ** 2).sum(dim=[1, 2, 3], keepdim=True).sqrt()+1e-8)*(latent_dim**0.5)
                            prev_sample = prev_latents_mean + prev_latents_std * prev_noise_mean
                            prev_latents_k = prev_sample
                            prev_latents.append(prev_latents_k)
                            
                        prev_latents = torch.cat(prev_latents, dim=0)
                        latents = prev_latents
                        torch.cuda.empty_cache()
                else:
                    pred_dict = ddim_step_fetch_x0(
                        self.scheduler,
                        noise_pred, 
                        t, 
                        latents, 
                    )
                    latents = ddim_step_fetch_x_t_1(
                        self.scheduler,
                        dtype=latents.dtype,
                        num_sample_per_step=1,
                        timestep=t,
                        **extra_step_kwargs,
                        **pred_dict,
                    )
                    if i == divert_start_step-1:
                        latents = latents.repeat(len(weights), 1, 1, 1)
                        if do_classifier_free_guidance:
                            prompt_embeds = torch.cat([
                                negative_prompt_embeds.repeat(len(weights), 1, 1),
                                log_prompt_embeds.repeat(len(weights), 1, 1),
                            ])

                if i == len(timesteps) - 1:
                    # num_sample_per_step*b, c, h, w
                    pred_x0 = self.vae.decode(
                        latents.to(self.vae.dtype) / self.vae.config.scaling_factor,
                        return_dict=False,
                        generator=generator,
                    )[0]
                    
                    preference_scores = self._compute_reward(
                        pred_x0, opt_func_name[1], pref_function[1],
                        extra_info, pred_x0.shape[0], compress_target, device
                    )
                    preference_score_logs = preference_scores
                    images = pred_x0
                        
            # call the callback, if provided
            if i == len(timesteps) - 1 or ((i + 1) > num_warmup_steps and (i + 1) % self.scheduler.order == 0):
                progress_bar.update()
                if callback is not None and i % callback_steps == 0:
                    callback(i, t, latents)
    
    if not output_type == "latent" and not is_noise_images:
        images, has_nsfw_concept = self.run_safety_checker(images, device, prompt_embeds.dtype)
    else:
        has_nsfw_concept = None
        
    if has_nsfw_concept is None:
        do_denormalize = [True] * images.shape[0]
    else:
        do_denormalize = [not has_nsfw for has_nsfw in has_nsfw_concept]
                
    if output_type == 'pil':
        images = self.image_processor.postprocess(images.detach(), output_type=output_type, do_denormalize=do_denormalize)
    
    if profiler is not None:
        profiler.end('pipeline_inference')

    return images, preference_score_logs


# Helper methods for reward computation and normalization
def _compute_reward(self, images, func_name, func, extra_info, batch_size, compress_target, device):
    """Compute reward for given function."""
    if func_name == 'compress':
        scores = func(images)
        scores = torch.tensor(scores, dtype=images.dtype).to(device)
    elif func_name == 'aes':
        scores = func(images, '')
    elif func_name == 'hps':
        prompts = [extra_info["prompts"]] * batch_size
        scores = func(images, prompts)
    elif func_name == 'clip' or func_name == 'pick':
        prompts = [extra_info["prompts"]] * batch_size
        scores = func(images, prompts)
    else:
        raise NotImplementedError(f"Unknown reward function: {func_name}")
    
    return scores


def _normalize_rewards(self, rewards_, norm_method, reward_target=None):
    """Normalize rewards according to specified method."""
    if reward_target is not None:
        mask = rewards_<reward_target
        if mask.sum() == 1:
            rewards_nor_ = torch.where(mask, torch.ones_like(rewards_), torch.zeros_like(rewards_))
            return rewards_nor_
        elif mask.sum() == 0:
            rewards_nor_ = torch.zeros_like(rewards_)
            rewards_nor_[0] = 1
            return rewards_nor_
        else:
            rewards = rewards_[mask]
    else:
        rewards = rewards_
        mask = torch.ones_like(rewards_, dtype=torch.bool)

    if norm_method == 'std':
        reward_mean = torch.mean(rewards)
        reward_std = torch.std(rewards, unbiased=False)+1e-8
        rewards_nor = (rewards_ - reward_mean) / reward_std
            
    elif norm_method == 'tanh':
        reward_mean = torch.mean(rewards)
        reward_std = torch.std(rewards, unbiased=False)+1e-8
        rewards_nor = torch.tanh((rewards_ - reward_mean) / reward_std)
    
    elif norm_method == 'minmax':
        reward_min = torch.min(rewards)
        reward_max = torch.max(rewards)
        rewards_nor = (rewards_ - reward_min) / (reward_max - reward_min+1e-8)
    
    else:
        raise NotImplementedError(f"Unknown normalization method: {norm_method}")
    
    rewards_nor_ = torch.where(mask, rewards_nor, torch.zeros_like(rewards_nor))

    return rewards_nor_

# Add helper methods to the pipeline class
StableDiffusionPipeline._compute_reward = _compute_reward
StableDiffusionPipeline._normalize_rewards = _normalize_rewards

