# Copied from https://github.com/huggingface/diffusers/blob/fc6acb6b97e93d58cb22b5fee52d884d77ce84d8/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
# with the following modifications:
# - It uses the patched version of `ddim_step_with_logprob` from `ddim_with_logprob.py`. As such, it only supports the
#   `ddim` scheduler.
# - It returns all the intermediate latents of the denoising process as well as the log probs of each denoising step.

from typing import Any, Callable, Dict, List, Optional, Union
import numpy as np
import torch

from diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion import (
    StableDiffusionPipeline,
    rescale_noise_cfg,
)

from .ddim_seperate_func import ddim_step_fetch_x0, ddim_step_fetch_x_t_1


@torch.no_grad()
def pipeline_with_logprob(
    self: StableDiffusionPipeline,
    prompt: Union[str, List[str]] = None,
    height: Optional[int] = None,
    width: Optional[int] = None,
    num_inference_steps: int = 50,
    guidance_scale: float = 7.5,
    negative_prompt: Optional[Union[str, List[str]]] = None,
    num_images_per_prompt: Optional[int] = 1,
    eta: float = 0.0,
    generator: Optional[Union[torch.Generator, List[torch.Generator]]] = None,
    latents: Optional[torch.FloatTensor] = None,
    prompt_embeds: Optional[torch.FloatTensor] = None,
    negative_prompt_embeds: Optional[torch.FloatTensor] = None,
    output_type: Optional[str] = "pil",
    return_dict: bool = True,
    callback: Optional[Callable[[int, int, torch.FloatTensor], None]] = None,
    callback_steps: int = 1,
    cross_attention_kwargs: Optional[Dict[str, Any]] = None,
    guidance_rescale: float = 0.0,
    is_noise_images: bool = False, 
    pref_function=None,
    opt_func_name=None,
    pref_guide=1.0,
    divert_start_step=0,
    extra_info=None,
    inner_steps=1,
    accelerator=None,
    method=None,
):
    r"""
    Function invoked when calling the pipeline for generation.

    Args:
        prompt (`str` or `List[str]`, *optional*):
            The prompt or prompts to guide the image generation. If not defined, one has to pass `prompt_embeds`.
            instead.
        height (`int`, *optional*, defaults to self.unet.config.sample_size * self.vae_scale_factor):
            The height in pixels of the generated image.
        width (`int`, *optional*, defaults to self.unet.config.sample_size * self.vae_scale_factor):
            The width in pixels of the generated image.
        num_inference_steps (`int`, *optional*, defaults to 50):
            The number of denoising steps. More denoising steps usually lead to a higher quality image at the
            expense of slower inference.
        guidance_scale (`float`, *optional*, defaults to 7.5):
            Guidance scale as defined in [Classifier-Free Diffusion Guidance](https://arxiv.org/abs/2207.12598).
            `guidance_scale` is defined as `w` of equation 2. of [Imagen
            Paper](https://arxiv.org/pdf/2205.11487.pdf). Guidance scale is enabled by setting `guidance_scale >
            1`. Higher guidance scale encourages to generate images that are closely linked to the text `prompt`,
            usually at the expense of lower image quality.
        negative_prompt (`str` or `List[str]`, *optional*):
            The prompt or prompts not to guide the image generation. If not defined, one has to pass
            `negative_prompt_embeds` instead. Ignored when not using guidance (i.e., ignored if `guidance_scale` is
            less than `1`).
        num_images_per_prompt (`int`, *optional*, defaults to 1):
            The number of images to generate per prompt.
        eta (`float`, *optional*, defaults to 0.0):
            Corresponds to parameter eta (η) in the DDIM paper: https://arxiv.org/abs/2010.02502. Only applies to
            [`schedulers.DDIMScheduler`], will be ignored for others.
        generator (`torch.Generator` or `List[torch.Generator]`, *optional*):
            One or a list of [torch generator(s)](https://pytorch.org/docs/stable/generated/torch.Generator.html)
            to make generation deterministic.
        latents (`torch.FloatTensor`, *optional*):
            Pre-generated noisy latents, sampled from a Gaussian distribution, to be used as inputs for image
            generation. Can be used to tweak the same generation with different prompts. If not provided, a latents
            tensor will ge generated by sampling using the supplied random `generator`.
        prompt_embeds (`torch.FloatTensor`, *optional*):
            Pre-generated text embeddings. Can be used to easily tweak text inputs, *e.g.* prompt weighting. If not
            provided, text embeddings will be generated from `prompt` input argument.
        negative_prompt_embeds (`torch.FloatTensor`, *optional*):
            Pre-generated negative text embeddings. Can be used to easily tweak text inputs, *e.g.* prompt
            weighting. If not provided, negative_prompt_embeds will be generated from `negative_prompt` input
            argument.
        output_type (`str`, *optional*, defaults to `"pil"`):
            The output format of the generate image. Choose between
            [PIL](https://pillow.readthedocs.io/en/stable/): `PIL.Image.Image` or `np.array`.
        return_dict (`bool`, *optional*, defaults to `True`):
            Whether or not to return a [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] instead of a
            plain tuple.
        callback (`Callable`, *optional*):
            A function that will be called every `callback_steps` steps during inference. The function will be
            called with the following arguments: `callback(step: int, timestep: int, latents: torch.FloatTensor)`.
        callback_steps (`int`, *optional*, defaults to 1):
            The frequency at which the `callback` function will be called. If not specified, the callback will be
            called at every step.
        cross_attention_kwargs (`dict`, *optional*):
            A kwargs dictionary that if specified is passed along to the `AttentionProcessor` as defined under
            `self.processor` in
            [diffusers.cross_attention](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/cross_attention.py).
        guidance_rescale (`float`, *optional*, defaults to 0.7):
            Guidance rescale factor proposed by [Common Diffusion Noise Schedules and Sample Steps are
            Flawed](https://arxiv.org/pdf/2305.08891.pdf) `guidance_scale` is defined as `φ` in equation 16. of
            [Common Diffusion Noise Schedules and Sample Steps are Flawed](https://arxiv.org/pdf/2305.08891.pdf).
            Guidance rescale factor should fix overexposure when using zero terminal SNR.

    Examples:

    Returns:
        [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] or `tuple`:
        [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] if `return_dict` is True, otherwise a `tuple.
        When returning a tuple, the first element is a list with the generated images, and the second element is a
        list of `bool`s denoting whether the corresponding generated image likely represents "not-safe-for-work"
        (nsfw) content, according to the `safety_checker`.
    """
    # 0. Default height and width to unet
    height = height or self.unet.config.sample_size * self.vae_scale_factor
    width = width or self.unet.config.sample_size * self.vae_scale_factor

    # 1. Check inputs. Raise error if not correct
    self.check_inputs(prompt, height, width, callback_steps, negative_prompt, prompt_embeds, negative_prompt_embeds)

    # 2. Define call parameters
    if prompt is not None and isinstance(prompt, str):
        batch_size = 1
    elif prompt is not None and isinstance(prompt, list):
        batch_size = len(prompt)
    else:
        batch_size = prompt_embeds.shape[0]

    device = self._execution_device
    # here `guidance_scale` is defined analog to the guidance weight `w` of equation (2)
    # of the Imagen paper: https://arxiv.org/pdf/2205.11487.pdf . `guidance_scale = 1`
    # corresponds to doing no classifier free guidance.
    do_classifier_free_guidance = guidance_scale > 1.0
    
    num_samples_each_step = 30
    temperature = 0.01
    # 3. Encode input prompt
    text_encoder_lora_scale = cross_attention_kwargs.get("scale", None) if cross_attention_kwargs is not None else None
    prompt_embeds, negative_prompt_embeds = self.encode_prompt(
        prompt,
        device,
        num_images_per_prompt,
        do_classifier_free_guidance,
        negative_prompt,
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        lora_scale=text_encoder_lora_scale,
    )
    log_prompt_embeds = prompt_embeds
    # For classifier free guidance, we need to do two forward passes.
    # Here we concatenate the unconditional and text embeddings into a single batch
    # to avoid doing two forward passes

    if do_classifier_free_guidance:
        prompt_embeds = torch.cat([negative_prompt_embeds, prompt_embeds])
        prev_prompt_embeds = torch.cat([
            negative_prompt_embeds.repeat(num_samples_each_step, 1, 1),
            log_prompt_embeds.repeat(num_samples_each_step, 1, 1),
        ])
    else:
        prev_prompt_embeds = log_prompt_embeds.repeat(num_samples_each_step, 1, 1)

    # 4. Prepare timesteps
    self.scheduler.set_timesteps(num_inference_steps, device=device)
    timesteps = self.scheduler.timesteps

    # 5. Prepare latent variables
    num_channels_latents = self.unet.config.in_channels
    latents = self.prepare_latents(
        batch_size * num_images_per_prompt,
        num_channels_latents,
        height,
        width,
        prompt_embeds.dtype,
        device,
        generator,
        latents,
    )

    # 6. Prepare extra step kwargs. TODO: Logic should ideally just be moved out of the pipeline
    extra_step_kwargs = self.prepare_extra_step_kwargs(generator, eta)

    # 7. Denoising loop
    num_warmup_steps = len(timesteps) - num_inference_steps * self.scheduler.order
    all_latents = [latents]
    all_log_probs = []
    preference_score_logs = []
    
    with (self.progress_bar(total=num_inference_steps) as progress_bar):
        for i, t in enumerate(timesteps):
            for j in range(inner_steps):
                # expand the latents if we are doing classifier free guidance
                latent_model_input = torch.cat([latents] * 2) if do_classifier_free_guidance else latents
                latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)

                # predict the noise residual
                noise_pred = self.unet(
                    latent_model_input,
                    t,
                    encoder_hidden_states=prompt_embeds,
                    cross_attention_kwargs=cross_attention_kwargs,
                    return_dict=False,
                )[0]
                
                # perform guidance
                if do_classifier_free_guidance:
                    noise_pred_uncond, noise_pred_text = noise_pred.chunk(2)
                    noise_pred = noise_pred_uncond + guidance_scale * (noise_pred_text - noise_pred_uncond)

                if do_classifier_free_guidance and guidance_rescale > 0.0:
                    # Based on 3.4. in https://arxiv.org/pdf/2305.08891.pdf
                    noise_pred = rescale_noise_cfg(noise_pred, noise_pred_text, guidance_rescale=guidance_rescale)

                if i >= divert_start_step:
                    pred_dict = ddim_step_fetch_x0(
                        self.scheduler,
                        noise_pred,
                        t,
                        latents,
                    )
                    all_prev_latents_noise = []
                    all_rewards = []
                    for k in range(30//num_samples_each_step):
                        prev_latents, prev_latents_mean, prev_latents_std, prev_latents_noise = ddim_step_fetch_x_t_1(
                            self.scheduler,
                            dtype=latents.dtype,
                            num_sample_per_step=num_samples_each_step,
                            timestep=t,
                            constrain_grad=False,
                            latents=latents,
                            accelerator=accelerator,
                            grad_method=method,  # fixed_coef
                            # grad_clip=7,
                            # reg_weight=0.1,
                            return_prev_mean=True,
                            **extra_step_kwargs,
                            **pred_dict,
                        )
                        all_prev_latents_noise.append(prev_latents_noise)
                        latent_model_input = torch.cat([prev_latents] * 2) if do_classifier_free_guidance else prev_latents
                        latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)
                        # predict the noise residual
                        noise_pred = self.unet(
                            latent_model_input,
                            t,
                            encoder_hidden_states=prev_prompt_embeds,
                            cross_attention_kwargs=cross_attention_kwargs,
                            return_dict=False,
                        )[0]
                        # perform guidance
                        if do_classifier_free_guidance:
                            noise_pred_uncond, noise_pred_text = noise_pred.chunk(2)
                            noise_pred = noise_pred_uncond + guidance_scale * (noise_pred_text - noise_pred_uncond)
                        if do_classifier_free_guidance and guidance_rescale > 0.0:
                            # Based on 3.4. in https://arxiv.org/pdf/2305.08891.pdf
                            noise_pred = rescale_noise_cfg(noise_pred, noise_pred_text, guidance_rescale=guidance_rescale)
                        prev_pred_dict = ddim_step_fetch_x0(
                            self.scheduler,
                            noise_pred,
                            t,
                            prev_latents,
                        )
                        # num_sample_per_step+1, c, h, w
                        prev_pred_x0 = prev_pred_dict['pred_original_sample']
                        prev_pred_x0 = self.vae.decode(
                            prev_pred_x0.to(self.vae.dtype) / self.vae.config.scaling_factor,
                            return_dict=False,
                            generator=generator,
                        )[0]
                        preference_timestep = t.repeat(prev_pred_x0.shape[0])
                        extra_info['timesteps'] = preference_timestep
                        if opt_func_name == 'ent':
                            preference_scores = pref_function(prev_pred_x0)
                        elif opt_func_name == 'compress':
                            preference_scores = pref_function(prev_pred_x0)
                            preference_scores = torch.tensor(preference_scores, dtype=torch.float).to(accelerator.device)
                        elif opt_func_name == 'aes':
                            preference_scores = pref_function.score(prev_pred_x0)
                        elif opt_func_name == 'hps':
                            preference_scores = pref_function.score(prev_pred_x0, extra_info["prompts"])
                        elif opt_func_name == 'pickscore':
                            preference_timestep = t.repeat(prev_pred_x0.shape[0])
                            extra_info['timesteps'] = preference_timestep
                            preference_scores = pref_function(prev_pred_x0, extra_info)
                        else:
                            pass
                        all_rewards.append(preference_scores)
                    prev_latents_noise = torch.cat(all_prev_latents_noise, dim=0)
                    preference_scores = torch.cat(all_rewards, dim=0)
                    # scores_mean = torch.mean(preference_scores)
                    # scores_std = torch.std(preference_scores)
                    # pref_scores_nor = (preference_scores - scores_mean) / scores_std
                    # pref_score_p = pref_scores_nor.reshape(-1, 1, 1, 1)
                    # prev_sample = prev_latents_mean + prev_latents_std * torch.sum(pref_score_p * prev_latents_noise/prev_latents_std,
                    #                                                                dim=0)
                    scores_mean = torch.mean(preference_scores)
                    scores_std = torch.std(preference_scores)
                    #pref_score_p = torch.tanh((preference_scores-scores_mean)/scores_std).reshape(-1, 1, 1, 1)
                    pref_score_p = ((preference_scores-scores_mean)/scores_std).reshape(-1, 1, 1, 1)
                    # scores_mean = torch.mean(preference_scores)
                    # scores_std = torch.std(preference_scores)
                    # pref_scores_nor = (preference_scores - scores_mean) / scores_std
                    # pref_score_p = torch.softmax(pref_scores_nor/temperature, dim=0).reshape(-1, 1, 1, 1)
                    # if accelerator.is_main_process:
                    #     print(pref_score_p.squeeze())
                    #     print(preference_scores)
                    prev_noise_mean = torch.sum(pref_score_p * prev_latents_noise, dim=0, keepdim=True)
                    latent_dim = np.prod(prev_latents.shape[1:])
                    prev_noise_mean = prev_noise_mean/(prev_noise_mean ** 2).sum(axis=[1, 2, 3], keepdim=True).sqrt()*(latent_dim**0.5)
                    prev_sample = prev_latents_mean + prev_latents_std * prev_noise_mean
                    latents = prev_sample
                    if i % 10 == 0 or i == len(timesteps)-1:
                        print(torch.mean(preference_scores), torch.max(preference_scores), prev_noise_mean.norm(), t)
                else:
                    pred_dict = ddim_step_fetch_x0(
                        self.scheduler,
                        noise_pred, 
                        t, 
                        latents, 
                    )
                    latents = ddim_step_fetch_x_t_1(
                        self.scheduler,
                        dtype=latents.dtype,
                        num_sample_per_step=1,
                        timestep=t,
                        **extra_step_kwargs,
                        **pred_dict,
                    )

                if i == len(timesteps) - 1:
                    # num_sample_per_step*b, c, h, w
                    pred_x0 = self.vae.decode(
                        latents.to(self.vae.dtype) / self.vae.config.scaling_factor,
                        return_dict=False,
                        generator=generator,
                    )[0]
                    if opt_func_name == 'ent':
                        preference_scores = pref_function(pred_x0)
                    elif opt_func_name == 'compress':
                        preference_scores = pref_function(pred_x0)
                        preference_scores = torch.tensor(preference_scores, dtype=torch.float).to(accelerator.device)
                    elif opt_func_name == 'aes':
                        preference_scores = pref_function.score(pred_x0)
                    elif opt_func_name == 'hps':
                        preference_scores = pref_function.score(pred_x0, extra_info["prompts"])
                    elif opt_func_name == 'pickscore':
                        preference_timestep = t.repeat(pred_x0.shape[0])
                        extra_info['timesteps'] = preference_timestep
                        preference_scores = pref_function(pred_x0, extra_info)
                    else:
                        pass
                    images = pred_x0
                    preference_score_logs = preference_scores
                    # print(preference_scores)
                        
            # call the callback, if provided
            if i == len(timesteps) - 1 or ((i + 1) > num_warmup_steps and (i + 1) % self.scheduler.order == 0):
                progress_bar.update()
                if callback is not None and i % callback_steps == 0:
                    callback(i, t, latents)
    
    if not output_type == "latent" and not is_noise_images:
        images, has_nsfw_concept = self.run_safety_checker(images, device, prompt_embeds.dtype)
    else:
        has_nsfw_concept = None
        
    if has_nsfw_concept is None:
        do_denormalize = [True] * images.shape[0]
    else:
        do_denormalize = [not has_nsfw for has_nsfw in has_nsfw_concept]
                
    if output_type == 'pil':
        images = self.image_processor.postprocess(images.detach(), output_type=output_type, do_denormalize=do_denormalize)                
    
    return images, preference_score_logs
